pipeline {   
  agent {
    node {
      label 'master'
    }  
  }
  stages {
    stage('checkout') {
      steps {
        checkout scm
        sh 'docker pull cytopia/terragrunt'
      }
    }
    stage('plan') {
      steps {
        sh 'docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                -v /my/tf:/data -w /data/mysql cytopia/terragrunt terragrunt plan-all --terragrunt-non-interactive'
      }
    }

    stage('approval') {
      options {
        timeout(time: 1, unit: 'HOURS') 
      }
      steps {
        input 'approve the plan to proceed and apply'
      }
    }
    stage('apply') {
      steps {
        sh 'docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                    -v /my/tf:/data -w /data/mysql cytopia/terragrunt terragrunt apply --terragrunt-non-interactive'
        cleanWs()
      }
    }
  }
}
